site_name: microservice-py-docker
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: green
      toggle:
        name: Switch to light mode
        icon: material/lightbulb-outline
    - scheme: slate
      primary: blue
      accent: green
      toggle:
        name: Switch to dark mode
        icon: material/lightbulb
  features:
    - toc.follow
    - navigation.top
    - navigation.tracking
    - search.highlight
    - content.tabs.link
    - navigation.tabs
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
repo_url: https://github.com/yemaney/microservice-py-docker
repo_name: yemaney/microservice-py-docker
plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    handlers:
      python:
        options:
          members_order: source
          docstring_style: numpy
          separate_signature: true
          show_signature_annotations: true
          show_labels: true
          show_bases: true
          show_symbol_type_toc: true
          show_symbol_type_heading: true